config/routes.rb
require 'sidekiq/web' if Rails.env.development?

Mostre::Application.routes.draw do

  mount Sidekiq::Web, at: "/sidekiq" if Rails.env.development?

  scope '/cultura' do
    get '', to: "cultura#index"
    post '/inscrever', to: "cultura#inscrever"
    resources :incentivos
    resources :entidades
    resources :projetos
    get "/cidades/:uf/:nome", to: "cultura#cidade"
    get "/proponentes", to: "entidades#proponentes"
    get "/patrocinadores", to: "entidades#patrocinadores"
    get "/salicnet/:numero", to: "cultura#salicnet"
  end
  get 'visu.json', to: "cultura#visu"

  scope '/educacao' do
    get '', to: "educacao#index"
    resources :cursos
    resources :mantenedoras
    resources :instituicaos
    get "/mantenedoras", to: "mantenedoras#index"
    get "/instituicoes", to: "instituicaos#index"
    get "/cursos", to: "cursos#index"
  end

  scope '/eleicoes' do
      get '', to: "eleicoes#index"
      get "/doadores", to: "doadores#index"
      get "/doadores/:id", to: "doadores#show"      
      # get "/partidos", to: "partidos#index"
      # get "/partidos/:partido", to: "partidos#show"
      get "/candidatos", to: "candidatos#index"
      get "/candidatos/:id", to: "candidatos#show"
      #get "/comites", to: "eleicoes#comites"
    end

  get '/links', to: "links#index"
  get '/links/stats', to: "links#stats"
  get '/links/info/:link', to: "links#info"
  get '/:link', to: "links#show"
  resources :links

  root to: 'cultura#root'
end

app/models/projeto.rb
class Projeto < ApplicationRecord
	belongs_to :entidade, :touch => true
	belongs_to :estado
	belongs_to :segmento
	belongs_to :area

	has_many :incentivos
	# has_many :apoiadores, :source => :entidade, :through => :incentivos

	is_impressionable :counter_cache => true, :unique => true

	#default_scope -> {order('situacao_at DESC')}
	scope :aprovados, -> { where('apoiado > 0') }
	scope :ordenado, -> { order('situacao_at ASC') }

	validates_uniqueness_of :numero
	validates_presence_of :nome, :numero, :entidade_id, :uf, :area, :segmento, :processo, :mecanismo, :sintese, :solicitado,
		:aprovado, :apoiado, :sintese

	before_save :set_meta_attrs

	def set_meta_attrs
		self.urlized = self.nome.urlize
		self.estado_id = Estado.find_by_sigla(self.uf).id unless self.estado
		#self.liberado = self.mecanismo == 'FNC' || self.mecanismo == 'Recurso do Tesouro' || self.liberado_at
	end

	def to_param
		"#{self.id}-#{self.urlized}"
	end

  def expire_cache
    cache = "#{ActionController::Base.cache_store.cache_path}/cultura/projetos/#{self.to_param}.html"
    File.delete cache if File.exists? cache
  end

end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show]
  caches_page :show
  layout "cultura"

  def resumo
    estado = params[:estado_id] ? "em " + Estado.find(params[:estado_id]).nome : ''
    area = params[:area_id] ? "para " + Area.find(params[:area_id]).nome : ''
    soma = view_context.number_to_currency(@projetos.sum(:apoiado), :unit => "R$")
    "#{@projetos.count} projetos #{valor('nome')} #{is('liberados')} #{estado} #{area} com #{soma} em apoios."
  end

  def impor_filtros!
    #todo: refinar com switch

    if nome = params[:nome]
      @projetos = @projetos.where("projetos.nome like ?", "%#{nome}%")
    end

    if sintese = params[:sintese]
      @projetos = @projetos.where("projetos.sintese like ?", "%#{sintese}%")
    end

    if providencia = params[:providencia]
      @projetos = @projetos.where("projetos.providencia like ?", "%#{providencia}%")
    end

    # somente liberados
    if imposed? :liberados
      @projetos = @projetos.where('liberado_at IS NOT NULL')
    end

    if imposed? :fnc
      @projetos = @projetos.where('mecanismo = "FNC"')
    end

    if imposed? :recurso_tesouro
      @projetos = @projetos.where('mecanismo = "Recurso do Tesouro"')
    end

    #apoiado_maior_aprovado
    if imposed? :apoiado_maior_aprovado
      @projetos = @projetos.where('(apoiado > aprovado) and (aprovado > 0)')
    end

    if imposed? :apoiado_maior_zero
      @projetos = @projetos.where('apoiado > 0')
    end

    if imposed? :apoiadores_maior_20
      @projetos = @projetos.where('apoiadores > 20')
    end

    if imposed? :area_id
      @projetos = @projetos.where(area_id: params[:area_id])
    end

    if imposed? :estado_id
      @projetos = @projetos.where(estado_id: params[:estado_id])
    end

  end

  def index
    @title = "Projetos"
    page = params[:page] || 1

    if ordem = params[:ordem]
      ordem = "#{ordem} DESC"
    end

    @projetos = Projeto.includes(:entidade).order(ordem).paginate(page: page, per_page: 35)
    impor_filtros!

    unless params[:estado_id]
      #todo: benchmark group(:estado)
      por_estados = @projetos.includes(:estado).select('estado.nome, count(estado_id) DESC as count').group('estados.id').order('count(estado_id) DESC').references(:estados)
      @estados = {}
      Estado.all.each{|e| @estados[e] = por_estados.count[e.id] || 0}
      @estados = @estados.sort_by{|k, v| v}.reverse
    else
      @estado = Estado.find params[:estado_id]
    end

    unless params[:area_id]
      @areas = {}
      por_area = @projetos.joins(:segmento, :area).select('`areas`.`nome`').group('`areas`.`id`').count
      Area.all.each{|a| @areas[a] = por_area[a.id] || 0}
      @areas = @areas.sort_by{|k, v| v}.reverse
    else
      @area = Area.find params[:area_id]
    end

    @topo = resumo
    render layout: false if request.xhr?
  end

  def show
    apoiadores = "com #{@projeto.apoiadores} apoiadores" if @projeto.apoiadores
    @resumo = "Projeto em #{@projeto.estado.nome} #{apoiadores} por #{@projeto.mecanismo} em #{@projeto.area.nome} - #{@projeto.segmento.nome}"
    #impressionist @projeto
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
      @title = @projeto.nome
    end

    # Only allow a trusted parameter "white list" through.
    def projeto_params
      params.require(:projeto).permit(:nome, :proponente_id, :numero, :uf, :area, :mecanismo, :enquadramento, :segmento, :processo, :date, :situacao, :providencia, :sintese, :solicitado, :aprovado, :apoiado, :date)
    end
end

app/views/projetos/_list.haml
- @projetos ||= projetos

%table.table.table-striped.table-bordered.table-condensed.borda
  %thead
    %tr
      %th{style: 'width: 420px'} Projeto
      %th Estado
      %th Segmento
      %th#situacao_at.reorder Ano
      %th#solicitado.reorder Solicitado
      %th#aprovado.reorder Aprovado
      %th#apoiado.reorder Apoiado
      %th#apoiadores.reorder Incentivos
      %th#liberado_at.reorder{style: 'width: 85px'} Liberado

  %tbody
    - @projetos.each do |projeto|
      %tr
        - nome = hl(params[:nome], projeto.nome) if params[:nome]
        %td
          = link_to (nome || projeto.nome), projeto_path(projeto)
          %br
          = link_to projeto.entidade.nome, entidade_path(projeto.entidade), class: 'sub'
        %td= projeto.estado.sigla
        %td= projeto.segmento.nome
        %td
          - if projeto.situacao_at
            = projeto.situacao_at.year
          - else
            %span.badge.badge-warning em avaliação

        %td= reais projeto.solicitado
        - if projeto.aprovado > 0
          %td= reais projeto.aprovado
        - else
          %td
            - if especial(projeto)
              %span -
            - else
              %span.badge.badge-important 0
        %td
          - if projeto.apoiado > 0
            = reais projeto.apoiado
          - else
            - if projeto.aprovado > 0
              %span.badge.badge-important 0
            - else
              // sem aprovação e sem apoio
              %span -
        %td
          - #todo: visualizar se soma de apoiadores não bate com apoiado.
          - if projeto.apoiado > 0 && projeto.apoiadores==0
            - if especial(projeto)
              %span -
            - else
              %span.badge.badge-important
                %i.icon-question-sign
          - else
            - if apoiadores=projeto.apoiadores
              %span.badge.badge-info= apoiadores
            - else
              - if !apoiadores && !especial(projeto) && projeto.apoiado>0
                %span.badge.badge-important 0
              - else
                %span -
        %td
          - if at = projeto.liberado_at
            %span.badge.badge-success= at
          - else
            - if (especial(projeto))
              %span.badge.badge-warning
                %i.icon-star
            - else
              %span.badge.badge-important
                %i.icon-ban-circle

app/views/projetos/index.haml
- content_for :filtro do
  = render :partial => 'filtros/projetos'

.well.borda.status
  = @topo

= render :partial => 'list'
= pagination @projetos

#subfiltros
  - unless params[:area_id]
    #areas
      .well.borda
        %i.icon-tags
        Areas
        %hr.small

        - @areas.each do |a|
          - area = a[0]
          - count = a[1]
          %p.selectable{type: 'area', type_id: area.id}
            %span.rotulo= area.nome
            - if count > 0
              %span.badge.badge-right.badge-info= count
            - else
              %span.badge.badge-right.badge-important= count

  - unless params[:estado_id]
    #estados
      .well.borda
        %i.icon-globe
        Estados
        %hr.small
        - @estados.each do |e|
          - estado = e[0]
          - count = e[1]
          %p.selectable{type: 'estado', type_id: estado.id}
            %span.rotulo= estado.nome
            - if count > 0
              %span.badge.badge-right.badge-info= count
            - else
              %span.badge.badge-right.badge-important= count

app/views/projetos/index.html.haml
- content_for :filtro do
  = render :partial => 'filtros/projetos'

.well.borda.status
  = @topo

= render :partial => 'list'
= pagination @projetos

#subfiltros  
  - unless params[:area_id]
    #areas
      .well.borda
        %i.icon-tags
        Areas
        %hr.small
        
        - @areas.each do |a|
          - area = a[0]
          - count = a[1]
          %p.selectable{type: 'area', type_id: area.id}
            %span.rotulo= area.nome
            - if count > 0
              %span.badge.badge-right.badge-info= count
            - else
              %span.badge.badge-right.badge-important= count

  - unless params[:estado_id]
    #estados
      .well.borda
        %i.icon-globe
        Estados
        %hr.small
        - @estados.each do |e|
          - estado = e[0]
          - count = e[1]
          %p.selectable{type: 'estado', type_id: estado.id}
            %span.rotulo= estado.nome        
            - if count > 0
              %span.badge.badge-right.badge-info= count
            - else
              %span.badge.badge-right.badge-important= count

app/views/projetos/show.haml
:javascript
  $(document).ready(function(){
    $('th').removeClass('reorder')
  })

.well.status.borda
  .titulo
    %i.icon-th.afastado
    = @projeto.nome

.well.center.borda
  #title{style:"font-size:15px"}
    %a{href: '/cultura/entidades/' + @projeto.entidade.to_param}
      %i.icon-briefcase
      = "#{@projeto.entidade.nome} (#{@projeto.entidade.projetos_count})"

.center{style: "padding-bottom:10px"}
  - solicitou = @projeto.solicitado > 0 ? (reais @projeto.solicitado) : "nada"
  .label.label-warning= "Solicitou #{solicitou}"
  - if @projeto.aprovado > 0
    .label.label-info= "Aprovaram #{reais @projeto.aprovado}"
  - else
    - if !especial(@projeto)
      .label.label-important= "Sem aprovação"

  - if @projeto.apoiado > 0
    .label.label-success= "Conseguiu #{reais @projeto.apoiado}"
  - else
    - if !especial(@projeto)
      .label.label-important= "Conseguiu nada"

.well.status
  = @resumo

.alert.alert-info.borda
  %button.close{"data-dismiss" => "alert", type: "button"} ×
  %i.icon-pencil
  = @projeto.sintese

#infos.borda{style:"margin-top:8px"}
  - if @projeto.liberado_at
    .alert.alert-success
      %button.close{"data-dismiss" => "alert", type: "button"} ×
      %i.icon-ok
      = "Liberado em #{@projeto.liberado_at}"

.alert.borda
  %button.close{"data-dismiss" => "alert", type: "button"} ×
  %i.icon-exclamation-sign
  %strong= @projeto.situacao_at
  - enquadramento = "» #{@projeto.enquadramento}" if @projeto.enquadramento
  = " #{enquadramento} » #{@projeto.situacao} » #{@projeto.providencia}"


- if @projeto.apoiadores && @projeto.apoiadores > 0
  %table.table.table-striped.borda
    %thead
      %tr
        %th
        %th{style:'text-align:left'} Patrocinador
        %th Valor Total
        %th Depósitos
        %th Último
    %tbody
      - @projeto.incentivos.each do |i|
        %tr
          %td
            - if i.entidade.empresa
              %i.icon-briefcase
            - else
              %i.icon-user
          %td{style:'text-align:left'}= link_to_entidade i.entidade
          %td= reais i.valor
          %td= i.recibos_count
          - if last_recibo_at = i.last_recibo_at
            %td= to_date last_recibo_at
          - else
            %td -

.center
  %a.btn{href: "/cultura/salicnet/#{@projeto.numero}", target:"_blank"}
    %i.icon-info-sign
    Ver no SalicNet
  %br
  %br

app/views/projetos/show.html.haml
:javascript
  $(document).ready(function(){
    $('th').removeClass('reorder')
  })

.well.status.borda
  .titulo
    %i.icon-th.afastado
    = @projeto.nome

.well.center.borda
  #title{style:"font-size:15px"}
    %a{href: '/cultura/entidades/' + @projeto.entidade.to_param}
      %i.icon-briefcase
      = "#{@projeto.entidade.nome} (#{@projeto.entidade.projetos_count})"

.center{style: "padding-bottom:10px"}
  - solicitou = @projeto.solicitado > 0 ? (reais @projeto.solicitado) : "nada"
  .label.label-warning= "Solicitou #{solicitou}"
  - if @projeto.aprovado > 0
    .label.label-info= "Aprovaram #{reais @projeto.aprovado}"
  - else
    - if !especial(@projeto)
      .label.label-important= "Sem aprovação"

  - if @projeto.apoiado > 0
    .label.label-success= "Conseguiu #{reais @projeto.apoiado}"
  - else
    - if !especial(@projeto)
      .label.label-important= "Conseguiu nada"

.well.status
  = @resumo

.alert.alert-info.borda
  %button.close{"data-dismiss" => "alert", type: "button"} ×
  %i.icon-pencil
  = @projeto.sintese

#infos.borda{style:"margin-top:8px"}
  - if @projeto.liberado_at
    .alert.alert-success
      %button.close{"data-dismiss" => "alert", type: "button"} ×
      %i.icon-ok
      = "Liberado em #{@projeto.liberado_at}"

.alert.borda
  %button.close{"data-dismiss" => "alert", type: "button"} ×
  %i.icon-exclamation-sign
  %strong= @projeto.situacao_at
  - enquadramento = "» #{@projeto.enquadramento}" if @projeto.enquadramento
  = " #{enquadramento} » #{@projeto.situacao} » #{@projeto.providencia}"


- if @projeto.apoiadores && @projeto.apoiadores > 0
  %table.table.table-striped.borda
    %thead
      %tr
        %th
        %th{style:'text-align:left'} Patrocinador
        %th Valor Total
        %th Depósitos
        %th Último
    %tbody
      - @projeto.incentivos.each do |i|
        %tr
          %td
            - if i.entidade.empresa
              %i.icon-briefcase
            - else
              %i.icon-user
          %td{style:'text-align:left'}= link_to_entidade i.entidade
          %td= reais i.valor
          %td= i.recibos_count
          - if last_recibo_at = i.last_recibo_at
            %td= to_date last_recibo_at
          - else
            %td -

.center
  %a.btn{href: "/cultura/salicnet/#{@projeto.numero}", target:"_blank"}
    %i.icon-info-sign
    Ver no SalicNet
  %br
  %br